packaging_format = 2

id = "shlink"
name = "Shlink"
description.en = "Self-hosted URL shortener"
description.fr = "Raccourcisseur d'URL auto-hébergé"

version = "3.4.0~ynh2"

maintainers = []

[upstream]
license = "MIT"
website = "https://shlink.io/"
userdoc = "https://shlink.io/documentation/"
code = "https://github.com/shlinkio/shlink"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.front]
        url = "https://github.com/shlinkio/shlink-web-client/releases/download/v3.7.3/shlink-web-client_3.7.3_dist.zip"
        sha256 = "c843f34854a2b84fc63a8ba34073b8fe533962052feb01880bf0683846f2c612"

        [resources.sources.main]
        url = "https://github.com/shlinkio/shlink/releases/download/v3.4.0/shlink3.4.0_php8.1_dist.zip"
        sha256 = "e37e91cd86a8d495952783d1eeb94f157ddfe42f50849a3c2f979b1f9d991963"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "postgresql php8.2-apcu php8.2-fpm php8.2-pgsql php8.2-gd php8.2-common php8.2-curl php8.2-intl php8.2-gmp php8.2-xml php8.2-json"

    [resources.database]
    type = "postgresql"
