packaging_format = 2

id = "shlink"
name = "Shlink"
description.en = "Self-hosted URL shortener"
description.fr = "Raccourcisseur d'URL auto-hébergé"

version = "4.0.2~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://shlink.io/"
userdoc = "https://shlink.io/documentation/"
code = "https://github.com/shlinkio/shlink"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.front]
        url = "https://github.com/shlinkio/shlink-web-client/releases/download/v4.0.1/shlink-web-client_4.0.1_dist.zip"
        sha256 = "c4b9943664dae05b92f228d3a20e42c417189f42bc90f2b723b6777926fca81c"
        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/shlinkio/shlink-web-client"
        autoupdate.asset = "^shlink-web-client_.*_dist.zip$"

        [resources.sources.main]
        url = "https://github.com/shlinkio/shlink/releases/download/v4.0.2/shlink4.0.2_php8.2_dist.zip"
        sha256 = "9f020aef9847d534a9233d89742cdbbf681377ed3aed52edc77966dd656682e0"
        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/shlinkio/shlink"
        autoupdate.asset = "^shlink.*_php8.2_dist.zip$"
        

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "postgresql php8.2-apcu php8.2-pgsql php8.2-gd php8.2-curl php8.2-intl php8.2-gmp php8.2-xml"

    [resources.database]
    type = "postgresql"
