packaging_format = 2

id = "shlink"
name = "Shlink"
description.en = "Self-hosted URL shortener"
description.fr = "Raccourcisseur d'URL auto-hébergé"

version = "4.2.2~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://shlink.io/"
userdoc = "https://shlink.io/documentation/"
code = "https://github.com/shlinkio/shlink"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.front]
        url = "https://github.com/shlinkio/shlink-web-client/releases/download/v4.2.1/shlink-web-client_4.2.1_dist.zip"
        sha256 = "12f5707abc1f3e2de3ab99c219e118e577f02b12bd80f828b8e298c4b7d761b0"
        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/shlinkio/shlink-web-client"
        autoupdate.asset = "^shlink-web-client_.*_dist.zip$"

        [resources.sources.main]
        url = "https://github.com/shlinkio/shlink/releases/download/v4.2.2/shlink4.2.2_php8.3_dist.zip"
        sha256 = "06e1c157016518a9ffcb9720d290cea119342b29828c5edf507fe0c6e9033552"
        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/shlinkio/shlink"
        autoupdate.asset = "^shlink.*_php8.3_dist.zip$"
        

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "postgresql, php8.3-apcu, php8.3-pgsql, php8.3-gd, php8.3-curl, php8.3-intl, php8.3-gmp, php8.3-xml"

    [resources.database]
    type = "postgresql"
